language: node_js
sudo: false
node_js:
  - "0.10.35"
before_install: npm install -g grunt-cli
script: 
  - grunt wintersmith:build
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt aws_s3:deploy || false'
